In [21]:
# -*- coding: utf-8 -*-
#NUMPY

#numpy is an open library used for numerical operations"""
#Ways to install any library is "pip install numpy" in command prompt, or to 
#see how many libraries are there in your machine type "pip freeze". """

#WAYS TO IMPORT NUMPY

In [3]:
import numpy

In [4]:
array([1,2,3,4,5,6])

NameError: name 'array' is not defined

In [ ]:
# the above thing will not work because this is not the right way of defining an array of numpy.

In [ ]:
#using direct numpy functions.

In [6]:
numpy.array([1,2,3,4,5,6])

In [10]:
#using Alias as np

In [8]:
import numpy as np

In [9]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [11]:
#NUMPY TAKES LESS MEMORY THAN LISTS.


In [12]:
import sys

In [13]:
u = range(1000)

In [20]:
#print(u)

In [19]:
#for i in u:
 #   print(i)

In [27]:
print(sys.getsizeof(5)*(len(u)))

28000


In [23]:
d=np.arange(100)

In [28]:
print(d.size*d.itemsize)

400


In [29]:
#NUMPY IS ALSO FASTER THAN LISTS.

In [36]:
#NUMPY VS LISTS(by checking BMI calculations)

In [37]:
heights = [1.76 , 1.65, 1.71]

In [38]:
weights = [91, 65,81]

In [39]:
BMI = weights/heights**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [40]:
#so above we saw in lists we can not perform any mathematical operations.

In [41]:
height_in_m = np.array([heights])

In [42]:
weight_in_kg = np.array([weights])

In [43]:
BMI = weight_in_kg/height_in_m**2

In [44]:
print(BMI)

[[29.37758264 23.87511478 27.70083102]]


In [ ]:
#so we saw how numpy is helpful in mathematical operations

In [ ]:
#NUMPY ARRAYS CAN ONLY 1 DATA TYPE

In [48]:
d = np.array([1,2.8,True,"hello"])

In [49]:
print(d)

['1' '2.8' 'True' 'hello']


In [ ]:
#see in this array of d , the higest priority was with strings , so it has eventually converted all other data types into strings.

In [50]:
d = np.array([1,2.8,True])

In [51]:
print(d)

[1.  2.8 1. ]


In [ ]:
#see in this array of d , the higest priority was with float , so it has eventually converted all other data types into floats.

In [52]:
d = np.array([1,True])

In [53]:
print(d)

[1 1]


In [ ]:
#see in this array of d , the higest priority was with integer, so it has eventually converted all other data types into integers.

In [ ]:
#ADDING TWO LISTS

In [54]:
list=[1,2,3,4]

In [55]:
list + list

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
#see in above line it has not added the values, instead of it has concated the values of it.

In [56]:
np_array = np.array([1,3,6,7])

In [57]:
np_array+np_array

array([ 2,  6, 12, 14])

In [ ]:
#see it has particularily added the values of their corresponding indexes.

In [ ]:
#SUBSETTING

In [58]:
BMI

array([[29.37758264, 23.87511478, 27.70083102]])

In [70]:
light_ppl = np.array(BMI<26)

In [71]:
print(light_ppl)

[[False  True False]]


In [81]:
import numpy as np

In [85]:
dash = [[200,180],[40,60],[45,90],[9.0,0]]

In [ ]:
#converting into 2-D array

In [89]:
np_dash = np.array(dash)

In [90]:
print(np_dash)

[[200. 180.]
 [ 40.  60.]
 [ 45.  90.]
 [  9.   0.]]


In [ ]:
#here,as we can see it has converted it into 2-D array. and the element 9.0 is in float , so it has converted all other elements into decimal type.

In [ ]:
#type

In [91]:
type(np_dash)

numpy.ndarray

In [ ]:
#shape

In [92]:
np_dash.shape

(4, 2)

In [ ]:
#SUBSETTING

In [94]:
#ARRAY_NAME[ROW NO][COL NO]

In [93]:
np_dash[0][1]

180.0

In [ ]:
#NUMPY ARRAYS SUBSETTING

In [ ]:
#ARRAY_NAME[ROW NO,COL NO]

In [96]:
np_dash[1,1]

60.0

In [ ]:
#its giving the value which is 1st row and 1st column

In [97]:
np_dash[:,1]

array([180.,  60.,  90.,   0.])

In [ ]:
#its giving all the values of entire column and ':' indicates all

In [ ]:
#DESCRYPTIVE STATISTICS

In [ ]:
#This will give mean.

In [99]:
np.mean(np_dash[:,0])

73.5

In [ ]:
#This will give median.

In [100]:
np.median(np_dash[:,0])

42.5

In [ ]:
#This will give correlation coefficient.

In [102]:
np.corrcoef(np_dash[:,:])

array([[ 1., -1., -1.,  1.],
       [-1.,  1.,  1., -1.],
       [-1.,  1.,  1., -1.],
       [ 1., -1., -1.,  1.]])

In [ ]:
#This will give std deviation.

In [107]:
np.std(np_dash[:,0])

74.32529851941396

In [ ]:
#ADDING TWO 2D MATRIX

In [109]:
x=[[2,3,4],[2,3,5],[1,5,4]]

In [110]:
np_x = np.array(x)

In [111]:
print(np_x)

[[2 3 4]
 [2 3 5]
 [1 5 4]]


In [112]:
y=[[2,3,4],[2,3,5],[1,5,4]]

In [113]:
np_y = np.array(y)

In [114]:
np_total = np_x + np_y

In [115]:
print(np_total)

[[ 4  6  8]
 [ 4  6 10]
 [ 2 10  8]]


In [ ]:
#multipyling 2D arrays  by a scalar

In [116]:
multiply = [2,3,4]

In [117]:
np_multiply = np_x * multiply

In [ ]:
#Here, the first element of multiply is getting multiplied with the element of 1st row,1st col

In [ ]:
# the second element of multiply is getting multiplied with the element of 1st row, 2nd col

In [ ]:
# the third element of multiply is getting multiplied with the element of 1st row, 3rd col

In [ ]:
#Here, the first element of multiply is getting multiplied with the element of 2nd row,1st col

In [ ]:
# the second element of multiply is getting multiplied with the element of 2nd row, 2nd col

In [ ]:
# the third element of multiply is getting multiplied with the element of 3rd row, 3rd col

In [118]:
print(np_multiply)

[[ 4  9 16]
 [ 4  9 20]
 [ 2 15 16]]


In [ ]:
#CONCATING NUMPY ARRAYS

In [ ]:
#creating an array with the help of tuples

In [120]:
x = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [121]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [122]:
y = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [127]:
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#with the help of vstack , it has concated two arrays vertically.

In [124]:
np.hstack((x,y))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [ ]:
#with the help of hstack , it has concated two arrays horizontally.

In [ ]:
#SOME COMMONLY USED FUNCTIONS

In [ ]:
#sum of all the elements in matrix x

In [129]:
x.sum()

90

In [ ]:
#max value of matrix x

In [130]:
x.max()

9

In [ ]:
#min value of matrix x

In [132]:
x.min()

1

In [ ]:
#variance of all elements in x

In [133]:
x.var()

6.666666666666667

In [ ]:
#to get all elements of 2D array in 1D array , we use a function called as "ravel"

In [134]:
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])